### ISSUE TITLE
Add a sites method to Explorer - From Google Form

### ISSUE THREAD

**Issue by SimonGoring** [NeotomaDB/Explorer#6]
I would like to be able to go in, the same way I do with datasetids, except with sites:  http://apps.neotomadb.org/explorer/?datasetid=1001 except use siteid=100 or something.  Pinging @spatialit

*This issue was autogenerated by the Google Form for [Features](https://docs.google.com/forms/d/e/1FAIpQLSdRNat6L9grRF0xU5gibkr26xq9jD9wyHgw_AWxhrgn0lWv7w/viewform)*
A notification has been sent to @SimonGoring.

**Comment by spatialit** [comment]
It already works and handles multiple ids: http://apps.neotomadb.org/explorer/?siteids=1001,1005

Same with datasetids: http://apps.neotomadb.org/explorer/?datasetids=1001,1004

Mike

From: Simon 
Sent: Friday, September 30, 2016 1:04 AM
To: NeotomaDB/Explorer 
Cc: Mike Anderson ; Mention 
Subject: [NeotomaDB/Explorer] Add a sites method to Explorer - From Google Form (#6)

I would like to be able to go in, the same way I do with datasetids, except with sites: http://apps.neotomadb.org/explorer/?datasetid=1001 except use siteid=100 or something. Pinging @spatialit

This issue was autogenerated by the Google Form for Features
A notification has been sent to @SimonGoring.

**Comment by SimonGoring** [comment]
Awesome, sorry about that :)

**Comment by spatialit** [comment]
Thanks fine. It’s my favorite kind of enhancement request – one that already exists:)
